export const DATA_TICKSIZE = 0.5;
export const GRID_LINES_TRANSPARENCY = 0.06;
export const DATE_BOX_WIDTH = 80;
export const HEADER_HEIGHT = 32;
export const PAGE_PADDING = 4;
export const CANDLE_WICK_THICKNESS = 1;
// export const CANDLE_BULL_COLOR = '#23c4ec'; // theme color
// export const CANDLE_BEAR_COLOR = '#13201e'; // theme color
export const CANDLE_BULL_COLOR = 'green'; // standard color
export const CANDLE_BEAR_COLOR = 'red'; // standard color
export const CANDLE_BORDER = true;
export const CANDLE_BORDER_COLOR = 'black';
