version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - yum install -y nodejs
      - cd defichart/frontend
      - yarn
  build:
    commands:
      - yarn build
      - scp dist/ /var/www/html/dist
